#!/usr/bin/env python3
"""
Generate the secrets the self-hosted Supabase stack needs.

Hosted Supabase handed you ANON_KEY and SERVICE_ROLE_KEY. Self-hosted, you mint
them yourself: both are HS256 JWTs signed with JWT_SECRET, differing only in the
`role` claim. PostgREST validates them with the same secret and assumes that
role, which is what makes RLS work.

    python3 scripts/supabase-keys.py            # print a ready-to-paste .env block
    python3 scripts/supabase-keys.py --years 5  # shorter key lifetime

Stdlib only, so it runs on the server without installing anything.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import secrets
import time


def b64url(raw: bytes) -> str:
    """JWTs use base64url with the padding stripped."""
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


def sign_jwt(payload: dict, secret: str) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    signing_input = ".".join(
        b64url(json.dumps(part, separators=(",", ":"), sort_keys=True).encode())
        for part in (header, payload)
    )
    signature = hmac.new(
        secret.encode(), signing_input.encode(), hashlib.sha256
    ).digest()
    return f"{signing_input}.{b64url(signature)}"


def role_key(role: str, secret: str, years: int) -> str:
    issued = int(time.time())
    return sign_jwt(
        {
            "role": role,
            "iss": "supabase",
            "iat": issued,
            "exp": issued + years * 365 * 24 * 3600,
        },
        secret,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--years", type=int, default=10, help="key lifetime in years (default 10)"
    )
    args = parser.parse_args()

    # GoTrue rejects secrets shorter than 32 characters.
    jwt_secret = secrets.token_hex(32)
    # Kept alphanumeric: this password ends up inside postgres:// URLs, where
    # punctuation would need percent-encoding.
    postgres_password = "".join(
        secrets.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        for _ in range(32)
    )

    print("# ---------------------------------------------------------------")
    print("# Generated by scripts/supabase-keys.py — store these in a password")
    print("# manager. Regenerating JWT_SECRET invalidates every existing key")
    print("# and signs every user out.")
    print("# ---------------------------------------------------------------")
    print(f"POSTGRES_PASSWORD={postgres_password}")
    print(f"JWT_SECRET={jwt_secret}")
    print(f"ANON_KEY={role_key('anon', jwt_secret, args.years)}")
    print(f"SERVICE_ROLE_KEY={role_key('service_role', jwt_secret, args.years)}")
    print()
    print("# The app's .env (Jenkins credential) needs:")
    print("#   NEXT_PUBLIC_SUPABASE_ANON_KEY = ANON_KEY")
    print("#   SUPABASE_SERVICE_ROLE_KEY     = SERVICE_ROLE_KEY")


if __name__ == "__main__":
    main()
